# Generated by Django 4.1.1 on 2022-09-18 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('costumer', models.CharField(blank=True, max_length=12, null=True)),
                ('dept', models.CharField(blank=True, max_length=12, null=True)),
                ('note', models.CharField(blank=True, max_length=12, null=True)),
                ('dept_total', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
