# Generated by Django 4.1.1 on 2022-09-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0003_alter_dept_costumer_alter_dept_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
