# Generated by Django 4.1.1 on 2022-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0004_delete_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='depts',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
