# Generated by Django 4.1.1 on 2022-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0005_api_depts_api_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='total',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
