# Generated by Django 4.1.1 on 2022-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0006_alter_api_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='notes',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='total',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
