# Generated by Django 4.1.1 on 2022-09-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0007_alter_api_notes_alter_api_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
